### ISSUE TITLE
param 1.6.0 prints warning message when used with libraries that use param.version and haven't been updated to the way of using the new param.version

### ISSUE THREAD

**Issue by ceball** [ioam/param#224]
<img width="1093" alt="screen shot 2018-04-06 at 7 48 27 pm" src="https://user-images.githubusercontent.com/1929/38438851-a1e1fe4a-39d3-11e8-8ac3-dcd7a29f1cad.png">

**Comment by jbednar** [comment]
It would be nice if only developers would see this message, not users, but I don't know any way to achieve that, so I'm not sure there is anything to fix...

**Comment by ceball** [comment]
I meant, the warning should be pink and blinking, like other warnings ;)

I think we should not be displaying this kind of confusing warning to users. It's just a print...how would a user even turn it off? I actually thought the new version.py was backwards compatible - I must have confused myself. What if I were to make param.version backwards compatible and release 1.6.1? Any objections? (Or hints that it's in some way not possible...)

**Comment by jbednar** [comment]
The new version is *mostly* backwards compatible, but the presence of the arguments that the print statement is testing for indicates that the corresponding calls need updating, because it's going to ignore them.  It would be great if the message would only appear for developers, not users, but as usual I have no idea how that could happen. (I guess we could be very fancy and detect .git in the project directory that's including version, but that's quite a bit magical!)  In any case I'm fine with turning off the message for now, while our own libraries catch up, but in the long run it does seem like something to warn about.
