### ISSUE TITLE
Automatic conversions upon setting?

### ISSUE THREAD

**Issue by thomasdeneux** [ioam/param#242]
I would be interested if some parameter classes can automatically convert values to fit their type.
For example:
```
class Param(param.Parameterized):
    a = param.Boolean()

p = Param()
p.a = 3  # Generates an error. What about automatic conversion to True?
```

Would this be in line with the philosophy of `param`, or are there reasons for strict assigments and no conversion?

**Comment by jlstevens** [comment]
My personal opinion here is that automatic type conversion would work counter to param's type checking functionality. What we *do* do in places is convert arguments passed into a class constructor before passing it up the ``param.Parameterized`` via ``super``. In other words, you can choose to promote types yourself if you wish without needing support for it at the param level...

**Comment by jbednar** [comment]
Strict validation is very much part of the design for Parameters; the idea is to catch user errors immediately, rather than to hide them and make things continue to operate but with bogus values.  E.g. if someone were to supply "False" to a param.Boolean, right now that's correctly an error, but with automatic conversion would very confusingly result in the Boolean value True (as bool("False")==True).   
In general, it's quite unclear what a user might mean by supplying "3" to a Boolean, rather than, say, supplying "bool(3)", where the intent is clear.

Of course, as @jlstevens indicates, one can always make a new subclass with different behavior.  E.g. you can make an AsBoolean class, which inherits from Boolean but overrides the validation so that the resulting value is always coerced into a Boolean.  Even though AsBoolean no longer verifies that meaningful input has been supplied, it still ensures that the result is Boolean, allowing downstream code to avoid further checking. Users can do this without needing any changes to Param; just declare subclasses as needed. 

We could also consider having Parameters accept a flag in their constructor (`coerce_inputs=True`) that attempts a type conversion on such inputs, but it seems like this will need implementation in every such class, and I'm not sure it's worth the change to the codebase that would be required.  I'd have to see a very compelling argument for a set of important use cases that such a feature would enable.  So for now I'll close this, but feel free to reopen it if you can lay out a good case for where this would be generally useful.

**Comment by thomasdeneux** [comment]
Right, the answers make fully sense.
