### ISSUE TITLE
Tuple does not work with allow_None

### ISSUE THREAD

**Issue by jlstevens** [ioam/param#99]
Wouldn't you expect this to work?

```python
class Test(param.Parameterized):
    val = param.Tuple(default=None, allow_None=True)

>>> t = Test()
>>> t.val = (1,2,4)

TypeError: %d format: a number is required, not tuple
```

This is incredibly annoying, as I am back to doing horrible things like this:

```python
  time = param.Tuple((0,)*9, length=9)
```

And checks against the default value like this:

```python
if self.time == (0,)*9:
            self.time = tuple(time.localtime())
```

Urgh!

**Comment by jbednar** [comment]
No, I would not expect that to work.  The code says "The length is determined by the initial default value, and is not allowed to change after instantiation.".  Since length=None by default, I would think that you are required to specify an explicit length if the default is None.  It looks to me like the constructor should have raised an error in this case, complaining that the length has not been set.  The error message is because length is not a number, but I think the problem should have been detected earlier, right when the Parameter was created.  

I don't see why you need to do (0,)*9; I can't see anything in the code that would require you to do that.  What's the problem with allow_None, if you do set length properly?  I don't see one at present.

**Comment by jbednar** [comment]
Seems to be working ok to me:

```python
>>> import param
>>> class Test(param.Parameterized):
...     val = param.Tuple(default=None, length=3)
... 
>>> t = Test()
>>> print t.val
None
>>> t.val = (1,2,4)
>>>

**Comment by jlstevens** [comment]
Ok, I got it working as you suggested. That said, I do think an error message about the ``length`` argument not being set (if ``None`` is default) could have helped me avoid confusion.

**Comment by jbednar** [comment]
Warning added in a97f8a2.  The default should also probably be None, but I won't change that now since we're considering making such a change across all classes.
